org.gradle.jvmargs      = -Xmx1G

#Fabric properties
minecraft_major_version = 1.21
minecraft_version       = 1.21
yarn_mappings           = 1
loader_version          = 0.15.11

#Mod properties
mod_version             = 1.5.6
maven_group             = de.siphalor
archives_base_name      = amecsapi

# Dependencies
lombok_version          = 1.18.32
fabric_api_version      = 0.100.3+1.21
mixinextras_version     = 0.2.0-rc.5
